### PR TITLE
Fix the audio and video filter arguments

### PR DESCRIPTION
**Pull request by handokochen**
Just a quick pull request to fix the `-af` and `-vf` arguments. They were flipped.

### CODE REVIEW

**Comment by bramp** [comment]
Argh, and there were no tests to catch that either. Would you mind adding these to one of the exist tests?

**Comment by handokochen** [comment]
Done: I added testExample8.

**Comment by bramp** [comment]
Thanks!

**Comment by MMauro94** [comment]
Hi, it looks like the current latest release (`0.6.2`) is from before this bug was fixed. Could you please create a release with this bug fixed?

**Comment by kaibadash** [comment]
@bramp Could you release v0.6.3 ?

**Pull request merged**
