### PR TITLE
Allow setting args per input

### PR DESCRIPTION
**Pull request by igracia**
This PR makes it possible to provide args for each separate input. The rationale behind this is that there are certain args that apply to an input, and must be set before that input. An exampe of this is `itsoffset`, which sets the input time for the offset.

### CODE REVIEW

**Comment by bramp** [comment]
Thanks for the pull request!

I see this is a quick fix to the issue, but I think it makes more sense to add a new FFmpegInputBuilder, which is returned from a addInput(..) call, similar to how addOutput(..) works. That would allow the InputBuilder to support additional options, validate them, etc.

**Comment by igracia** [comment]
Yes I agree. I thought about that too, but opted for the quickie ;-) I'll give it a go and submit a pr again.

**Comment by bramp** [comment]
Thanks, I appreciate it. Also if you can ensure it works in a backwards compatible way that'll be best. Oh and please write tests :) Thanks!

**Comment by igracia** [comment]
Will certainly do! This was just something to start the discussion, as the
tests are not even passing ;)

**Comment by igracia** [comment]
@bramp There are modifiers common to input/output. Have you considered creating an abstract `FFmpegFileBuilder`? Also, have you identified which are input-only? From [this](https://ffmpeg.org/ffmpeg.html) page I have identified this
```
-f fmt (input/output)
-i filename (input)
-stream_loop number (input)
-c[:stream_specifier] codec (input/output,per-stream)
-codec[:stream_specifier] codec (input/output,per-stream)
-t duration (input/output)
-ss position (input/output)
-sseof position (input/output)
-itsoffset offset (input)-pix_fmt[:stream_specifier] format (input/output,per-stream)
-sws_flags flags (input/output)
-hwaccel_device[:stream_specifier] hwaccel_device (input,per-stream)
-ar[:stream_specifier] freq (input/output,per-stream)
-ac[:stream_specifier] channels (input/output,per-stream)
-acodec codec (input/output)
-guess_layout_max channels (input,per-stream)
-scodec codec (input/output)
-re (input)
-muxdelay seconds (input)
-muxpreload seconds (input)
-accurate_seek (input)
-seek_timestamp (input)
-thread_queue_size size (input)
-discard (input)
```

**Comment by bramp** [comment]
It had occurred to me there was a lot of overlap between input and output. I would +1 some kind of shared class.

I don't have a full list of what parameters are valid input and output. I just check the same doc you are looking at. In fact, I had also thought about some way to scrap the official docs (or execute `ffmpeg -h`), and to automate the generation of the builder.

**Comment by igracia** [comment]
That would be great. Can give you a hand with that if you decide to go that way. In the meantime, I'll try with the common builder and so on.

**Comment by bramp** [comment]
I would absolutely lend a hand, however, I tend to work on this project in bursts (at weekends when I get time). If you have a specific design, etc, then I'll happily review. For now I don't have time to contribute anything more substantial.

**Comment by igracia** [comment]
@bramp I've created an `AbstractFFmpegStreamBuilder` from which to extend builders for both input and output streams. I'll try to come up with the common set of properties that both have, but would probably need some assessment on that list. So far, I've identified these that are common
```
  /**
   * -f fmt (input/output) -c[:stream_specifier] codec (input/output,per-stream)
   * -codec[:stream_specifier] codec (input/output,per-stream) -t duration (input/output) -ss
   * position (input/output) -sseof position (input/output) -itsoffset offset
   * (input)-pix_fmt[:stream_specifier] format (input/output,per-stream) -sws_flags flags
   * (input/output)
   * 
   * -ar[:stream_specifier] freq (input/output,per-stream) -ac[:stream_specifier] channels
   * (input/output,per-stream) -acodec codec (input/output) -scodec codec (input/output)
   */
```
and these will end up in the input builder
```
  /**
   * 
   * -re (input) 
   * -muxdelay seconds (input) 
   * -muxpreload seconds (input) 
   * -accurate_seek (input)
   * -seek_timestamp (input) 
   * -thread_queue_size size (input) 
   * -discard (input) 
   * -guess_layout_max channels (input,per-stream) 
   * -hwaccel_device[:stream_specifier] hwaccel_device (input,per-stream) 
   * -i filename (input) 
   * -stream_loop number (input)
   */
```

**Comment by igracia** [comment]
Moved all the output params out of the abstract builder. Will start with the input tomorrow! I won't be able to get all of them, but I'll try to include as many as possible.

Code coverage has also decreased. I'll fix that after putting the input builder.

**Comment by bramp** [comment]
Sorry I've been slow to review. Is this read for merging?

**Comment by igracia** [comment]
Not yet. I still have to finish the implementation of the `FFmpegInputBuilder`. It would be great if you could review the checks that are not passing.

**Comment by igracia** [comment]
@bramp It's almost impossible to rebase this to current changes. I'll keep trying, but I don't think I can do that at the same pace as you are adding new things. Could it be possible to merge this in two steps?

**Comment by bramp** [comment]
Sorry, I made some large changes of the last week. Happy to accept in smaller patches, but would like to keep the library compiling and passing tests as much as possible between commits.

**Comment by igracia** [comment]
@bramp Just redid the whole thing, without the input builder yet. I guess it would be good to merge this patch now so further changes can go in the right place.

**Comment by igracia** [comment]
@bramp could you take a look at this yesterday? I'd like to get started with another PR related to #81, and it would be great if I can do that over this patch.

**Comment by bramp** [comment]
I've reviewed it again, and it looks good.. I like that you split out the addVideoArgs, addAudioArgs. It looks like all tests continue to pass so that's good.

**Comment by igracia** [comment]
Thanks! I figured it would provide a cleaner build implementation.

I'll get back to the input builder as soon as I can.

**Comment by bramp** [comment]
Hey @igracia any follow up on the InputBuilder?

**Comment by igracia** [comment]
Sorry for the delay @bramp! Got caught up in a hell lot of work. I should resume the builder stuff in some weeks.

**Pull request merged**
