### PR TITLE
Adding support for frame data extraction into ffprobe command.

### PR DESCRIPTION
**Pull request by ndtreviv**
This also supports requirement mentioned in #138.

In this version `-show_frames` is included in the ffprobe command, and frame data is extracted and deserialised. This is accomplished by a new `FFmpegFrameDeserializer` class, which supports polymorphism in the frame types.

### CODE REVIEW

**Comment by ndtreviv** [comment]
It looks like https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-64bit-static.tar.xz doesn't exist anymore (404). This is why the travis build is failing. Weren't my code, guv, honest!

**Comment by ndtreviv** [comment]
I super-duper want this pretty please!

**Comment by sarat1669** [comment]
Can we merge this?

**Comment by psaisambasiva** [comment]
Can we please add this change

**Comment by bramp** [comment]
Sorry for the slow response. This change looks great. No comments, other than it now seems to have some simple merge conflicts. Please could you take a look.

**Comment by Euklios** [comment]
I'll close this, as the requested feature can be enabled using the new FFprobeBuilder.
Please re-open or create a new PR/issue if this should not be the case

**Pull request closed without merging**
