### PR TITLE
Replace animal-sniffer with javac parameter

### LINKED ISSUE #311: Replace animal sniffer with javac parameters
**Is your feature request related to a problem? Please describe.**
The animal-sniffer plugin is currently in maintenance mode, as described on their [github page](https://github.com/mojohaus/animal-sniffer).
The same functionality can easily be achieved using Javac or by configuring Maven correctly.
The last major release supported by animal sniffer is 8.
Release 11 doesn't have signatures, and 21 isn't supported without [patching their plugin](https://github.com/mojohaus/animal-sniffer/issues/268).
The only LTS release in between 17 has signatures, but there are conflicts in naming with Java 1.7, and the hosting registry is currently offline.

Additionally, this project is technically misconfigured.
The listed version is Java 8+. However, animal-sniffer still validates against Java 7.
This hinders the development of #269, and it confuses developers.

**Describe the solution you'd like**
I would replace animal-sniffer with the built-in Java/Maven equivalents.

**Describe alternatives you've considered**
We could upgrade the signatures to Java 8 for now.
Patch animal-sniffer and provide signatures ourselves in the future.
However, this wouldn't be recommendable, as the effort is relatively high.

### PR DESCRIPTION
**Pull request by Euklios**
This closes #311

### CODE REVIEW

**Review by bramp — COMMENTED** [review]
Sounds great, but quickly reading about this, doesn't the '--release' flag need to be set. Where is that now happening?

**Comment by Euklios** [comment]
> Sounds great, but quickly reading about this, doesn't the '--release' flag need to be set. Where is that now happening?

Interestingly, when testing, I had the same behaviour when specifying the source and target.
But according to the documentation, you also need `maven.compiler.release`.
I'll update the PR

**Comment by Euklios** [comment]
@bramp I've added the missing flag.
This Javac feature was introduced in Java 9, so we can't use it on jdk8.
I configured it so that it will only be applied for jdk 9+.
Version 8 is still supported, but without adding the flag. Compatibility is guaranteed by simply not having the classes of higher versions in that case.

Alternatively, we could also upgrade to a newer Java version

**Comment by bramp** [comment]
I'm really out of date with Java, what's the standard min supported version? Checking my go-to project guava, they still support Java 1.8+.

**Comment by Euklios** [comment]
LTS releases are:
 - 8
 - 11
 - 17
 - 21

It honestly depends. Many tooling and very static solutions are still using Java 8, which is basically the "never-touch"-systems.
More significant projects (with financial backing) usually tend to target the current LTS or one before (spring, for example, switched to Java 17 with the release of Spring Boot 3)

The only somewhat consistent overview of that topic (that I know of) is from [newrelic](https://newrelic.com/sites/default/files/2023-04/new-relic-2023-state-of-the-java-ecosystem-2023-04-20.pdf). Based on that: Java 11 would be the most LTS. Sadly, this was published a few months after the release of Java 17, which means adoption was still underway. I'm expecting an update next month, but I'm expecting a shift in adaptation towards 17.

The option of Multi-Release Jar Files allows newer versions to be added to an old project.
Example: (The baseline is on Java 8, so add a second implementation for Java 11, and the runtime will dispatch to the next lower version).
But that is more for performance improvements, and we don't have the time to support this setup.

My company is still running on Java 17, and we plan to upgrade it to Java 21.
We switched because the dependencies we rely upon started incorporating needed changes, but they already used Java 17.
We were running on Java 8 before.

I'm working on projects in my spare time using Java 17+.
The project I'm using this library in is currently running with Java 19 but already has a branch ready with Java 21.

**Comment by Euklios** [comment]
@bramp Something I'd like to add:
I would create a release before switching versions.

Additionally, I'm working on adding getters to all the data classes.
Java has made a lot of progress towards immutable data, which (based on the comments) is also a goal of this project.
However, these structures don't work with public properties.

So, my recommended roadmap would be:
- Add getters and mark public properties as deprecated
- Release
- Make properties private
- Switch Java version

**Comment by bramp** [comment]
Thanks for all the great info. I think I'll move a lot of this content into a bug #316 

As for this change, let's try and keep Java 8 support, but happy to use this change for Java 9+

**Pull request merged**
