### PR TITLE
adding movflags and copyinkf params

### PR DESCRIPTION
**Pull request by nsilberman**

### CODE REVIEW

**Comment by nsilberman** [comment]
hmmm, some issues with README or version number ? not sure what to do @bramp

**Comment by bramp** [comment]
Your change looks good! However, for some reason Travis is reporting the build broken. I need to fix that before I will accept.

Another comment. movflags is only applicable to mov, mp4, ismv? Thus far (as far as I know) all the arguments I set are generic, that apply to all containers. I don't have a good solution to ensuring that container specific settings can only be applied when that container is in use. So I might also think about that before accepting, unless you have suggests?

**Comment by nsilberman** [comment]
about `movflags`, good point. Why not add some test requirements like `checkNotNull` but for codecs
You can group codecs by "family" and maybe reference some options accepted for output (and maybe have to execute a ffprobe ?)

**Comment by bramp** [comment]
Thanks I accepted the PR. I still don't have a good solution for checking the correct Codec. I don't want to get into a situation where I need to know an extensive list of codecs.

**Comment by nsilberman** [comment]
👍

**Pull request merged**
