### PR TITLE
feat(builder): add parameter for user-agent in the builder

### PR DESCRIPTION
**Pull request by davinkevin**
This is necessary when trying to use ffmpeg with url which filter on user-agent (streaming service for example).

### CODE REVIEW

**Comment by davinkevin** [comment]
The second commit add a parameter on the probe method which also need user-agent modification

**Comment by bramp** [comment]
I had a hard time finding documentation for ffprobe accepting a user-agent flag, but I'm going to assume it does.

Also does ffprobe have many other arguments? If so perhaps we should create a builder for it as well.

Until then, I'm going to accept this. Thanks!

**Comment by davinkevin** [comment]
`ffprobe -h` give all the information, this is what I use to find the user-agent parameter : https://gist.github.com/davinkevin/f9c8a743778083e57b5eb9dbdb08b631

I also think a builder could be a better solution, do you want to create an issue for that ?

**Comment by bramp** [comment]
Feel free to create a issue for a FFProbe builder, but I don't think it is worth working on until we need lots of arguments.

**Pull request merged**
